name: Pipeline de CI/CD - Hackathon Plots

# on:
#   pull_request:
#     branches: [ "main" ]
#   push:
#     branches: [ "main" ]

on:
  workflow_dispatch:

jobs:
  build-test-and-publish:
    name: Build, Teste e Publicação da Imagem
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do código-fonte
        uses: actions/checkout@v4

      - name: 2. Configurar ambiente .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: 3. Restaurar dependências NuGet
        run: dotnet restore "Hackathon.Plots.slnx"

      #incluir após testes
      - name: 4. Executar todos os testes
        run: dotnet test "Hackathon.Plots.slnx" --no-restore --verbosity normal

      - name: 5. Login no Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 6. Construir e enviar imagem Docker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rm364070/fiap-pos-hackathon-plots:latest